# Generated by Django 5.2.3 on 2025-08-04 03:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boundaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm3_en", models.CharField(blank=True, max_length=255, null=True)),
                ("adm2_en", models.CharField(blank=True, max_length=255, null=True)),
                ("adm1_en", models.CharField(blank=True, max_length=255, null=True)),
                ("shape_area", models.FloatField(blank=True, null=True)),
                ("area_sqkm", models.FloatField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
