# Generated by Django 5.2.3 on 2025-08-04 07:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "no_rooms",
                    models.IntegerField(blank=True, max_length=255, null=True),
                ),
                ("available", models.CharField(blank=True, max_length=255, null=True)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
