# Generated by Django 5.2.3 on 2025-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locations",
            name="no_rooms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
