# Generated by Django 5.2.3 on 2025-08-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_alter_locations_no_rooms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locations",
            old_name="contact",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="locations",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LocationsImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="location_images/")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="houses.locations",
                    ),
                ),
            ],
        ),
    ]
