# Generated by Django 5.2.3 on 2025-08-04 15:30

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_rename_contact_locations_phone_locations_email_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="locations",
            index=models.Index(fields=["geom"], name="houses_loca_geom_37c425_idx"),
        ),
        migrations.AddIndex(
            model_name="locations",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geom"], name="houses_loca_geom_dfecd9_gist"
            ),
        ),
    ]
