# Generated by Django 5.2.3 on 2025-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_locations_houses_loca_geom_37c425_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="price_per_month",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
