# Generated by Django 5.2.3 on 2025-08-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0006_locations_price_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="area_per_sqm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="locations",
            name="no_unit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
