# Generated by Django 5.2.3 on 2025-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0007_locations_area_per_sqm_locations_no_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
