# Generated by Django 5.2.3 on 2025-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0008_locations_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locations",
            name="price_per_month",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
