# Generated by Django 5.2.3 on 2025-08-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0009_alter_locations_price_per_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locations",
            name="price_per_month",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
