# Generated by Django 5.2.3 on 2025-08-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0010_alter_locations_price_per_month"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locations",
            old_name="area_per_sqm",
            new_name="area_sqm",
        ),
        migrations.RenameField(
            model_name="locations",
            old_name="no_unit",
            new_name="no_units",
        ),
        migrations.RenameField(
            model_name="locations",
            old_name="price_per_month",
            new_name="rent_per_month",
        ),
    ]
