# Generated by Django 5.2.3 on 2025-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0011_rename_area_per_sqm_locations_area_sqm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locations",
            name="area_sqm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locations",
            name="rent_per_month",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
