# Generated by Django 5.2.3 on 2025-08-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0012_alter_locations_area_sqm_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Boundaries",
            new_name="Boundary",
        ),
        migrations.RenameModel(
            old_name="Locations",
            new_name="Location",
        ),
        migrations.RenameModel(
            old_name="LocationsImages",
            new_name="LocationImages",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="houses_loca_geom_35277d_idx",
            old_name="houses_loca_geom_37c425_idx",
        ),
        migrations.RenameIndex(
            model_name="location",
            new_name="houses_loca_geom_555e93_gist",
            old_name="houses_loca_geom_dfecd9_gist",
        ),
    ]
